export const DEFAULT_COLORS = [
  "Neutral Gray",
  "Primary Purple",
  "Secondary Purple",
  "Tertiary Purple",
  "Dark Purple",
  "Light Purple",
  "Soft Green",
  "Soft Yellow",
  "Soft Orange",
  "Soft Pink",
  "Soft Peach",
  "Soft Blue",
  "Soft Gray",
  "Vivid Purple",
  "Magenta Pink",
  "Bright Orange",
  "Ocean Blue",
  "Charcoal Gray",
  "Pure White",
  "Medium Gray",
  "Bright Blue",
  "Dark Charcoal",
  "Light Gray",
  "Silver Gray",
  "Sky Blue",
  "Dark Gray",
  "Mid Gray",
  "Bright Blue Accent",
  "Dark Gray 555",
  "Dark Gray 333",
  "Gray 888",
  "Light Gray F1",
  "Dark Gray 333 Short",
  "White",
  "Medium Gray 999",
  "Light Gray CCC",
  "Off White",
  "Light Gray F3",
  "Red",
  "Dark Gray 222",
  "Black Alpha",
  "Dark Black Alpha",
  "Dark Gray Alpha",
  "White Alpha",
  "Dark Gray 333 Alpha",
  "Transparent Gray",
  "Transparent White",
  "Cool Gray",
  "Transparent Black 1A"
]

export const REQUIRED_COLORS = 4