export const DEFAULT_COLORS = [
  "Red",
  "Orange",
  "Yellow",
  "Green",
  "Blue",
  "Purple",
  "Pink",
  "White",
  "Black",
  "Silver",
  "Gold",
  "Neutral Gray",
  "Primary Purple",
  "Secondary Purple",
  "Tertiary Purple",
  "Dark Purple",
  "Light Purple",
  "Soft Green",
  "Soft Yellow",
  "Soft Orange",
  "Soft Pink",
  "Soft Peach",
  "Soft Blue",
  "Soft Gray",
  "Vivid Purple",
  "Magenta Pink",
  "Bright Orange",
  "Ocean Blue"
]

export const REQUIRED_COLORS = 4