// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhzjroixyewaxbzqrpom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inloempyb2l4eWV3YXhienFycG9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMTgxNzQsImV4cCI6MjA0OTY5NDE3NH0.x_PTm_nqqHZ3qeozeOh5t-y256WXcetFYKw1cQ0ptjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);